# Generated by Django 4.0.1 on 2022-08-15 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['complete']},
        ),
    ]
